seo: 
  site_name: Tina's Amazing Blog
  title: Default SEO Title
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-text_color: '#301F0F'
  medium-text_color: '#C68546'
  light-text_color: '#F9F2EB'
  featured-text_color: '#606C38'
  dark_color: '#91452d'
  medium_color: '#DDB691'
  light_color: '#F9F2EB'
  v-light_color: '#f9f9f9'
  featured_color: '#91A95A'
  accent_color: '#D4DDBE'
