seo: 
  site_name: Tina's Amazing Blog
  title: Default SEO Title
  description: Default description
  keywords: Default
  social_image: /images/logo-OMPM.png
  author: PF
  favicon_image: /images/favicon-OMPM.png
social: 
  instagram_username: https://www.instagram.com/onememorypermile
  facebook_url: https://www.facebook.com/profile.php?id=61557339363740
  pinterest: https://www.pinterest.com/onememorypermile/